In [1]:
import pandas as pd
# Load the provided Excel file to extract the "Treatment Arm 1 Regimen" column for unique values
file_path = 'mayo/task1a.xlsx'

# Reading the Excel file
task1a_df = pd.read_excel(file_path)

# Extracting unique values from the "Treatment Arm 1 Regimen" column
unique_treatment_regimens = task1a_df['Treatment Arm 1 Regimen'].unique()
unique_treatment_regimens.tolist()

['Darolutamide 600mg BID; Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation',
 'Abiraterone acetate 1000mg OD + Prednisolone 5mg BID; Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation',
 'Apalutamide 240 OD; standard androgen deprivation',
 'Enzalutamide 160mg OD; Standard androgen deprivation',
 'Abiraterone acetate 1000mg OD + Prednisolone 5mg BID; Standard androgen deprivation',
 'Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation',
 'Enzalutamide 160mg OD; Abiraterone acetate 1000mg OD + Prednisolone 5mg BID; Standard androgen deprivation',
 'TAK 300 mg BD; Standard androgen deprivation',
 'Rx1: Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation; Rx2:Abiraterone acetate 1000mg OD + Prednisolone 5mg BID; Standard androgen deprivation']

In [16]:
# Revisiting the task1a.xlsx file with the specified rules:
# 1. Latest Data Preference: Select the row with the most recent data based on 'Year of Publication' for each NCT number.
# 2. Fallback Mechanism: If the most recent report lacks certain data values, use the next most recent report that contains these values.

# Loading the dataset again
task1a_df = pd.read_excel(file_path)

# Sorting the data by NCT and Year in descending order
task1a_sorted = task1a_df.sort_values(by=['NCT', 'Treatment Arm 1 Regimen', 'Year'], ascending=[True, True, False])


grouped = task1a_sorted.groupby(['NCT', 'Treatment Arm 1 Regimen'])
filled_df = grouped.apply(lambda g: g.bfill())
filled_df.reset_index(drop=True, inplace=True)


final_df = filled_df.drop_duplicates(subset=['NCT', 'Treatment Arm 1 Regimen'], keep='first')

final_df.head()

,NCT,PubMed ID,Trial Name,Author,Year,Original/Follow Up,Treatment Arm 1 Regimen,Mode of metastases - N (%) | Synchronous | Treatment,Mode of metastases - N (%) | Synchronous | Control,Mode of metastases - N (%) | Metachronous | Treatment,Mode of metastases - N (%) | Metachronous | Control,Volume of disease - N (%) | High | Treatment,Volume of disease - N (%) | High | Control,Volume of disease - N (%) | Low | Treatment,Volume of disease - N (%) | Low | Control
0,NCT00104715,26610858,GETUG-AFU15,Gravis G et al,2015,Follow up,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",128 (67),144 (75),62 (32),46 (24),92 (48),91 (47),100 (52),102 (53)
2,NCT00268476,35411939,STAMPEDE,James N et al,2022,Follow up,Abiraterone acetate 1000mg OD + Prednisolone 5...,466 (93),475 (95),35 (7),27 (5),243 (48.5),256 (51),206 (41.1),196 (39.0)
8,NCT00268476,34757812,STAMPEDE,Rush L et al,2020,Follow up,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",345 (95),688 (95),17 (5),54 (5),148 (41),320 (44),124 (34),238 (34)
11,NCT00268476,37142371,STAMPEDE,Attard E et al,2023,Follow up,Enzalutamide 160mg OD; Abiraterone acetate 100...,NaN,NaN,NaN,NaN,196 (42),209 (46),195 (42),162 (36)
12,NCT00309985,29384722,CHAARTED,Kyriakopoulos C et al,2018,Follow up,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",289 (72.8),286 (72.8),108 (27.2),106 (27.0),263 (66.2),250(63.6),134 (33.8),143 (36.4)

In [17]:
task1a_sorted = final_df.sort_values(by=['NCT', 'Treatment Arm 1 Regimen', 'Year'], ascending=[True, True, False])
latest_records = task1a_sorted.groupby(['NCT', 'Treatment Arm 1 Regimen']).first().reset_index()
latest_records

,NCT,Treatment Arm 1 Regimen,PubMed ID,Trial Name,Author,Year,Original/Follow Up,Mode of metastases - N (%) | Synchronous | Treatment,Mode of metastases - N (%) | Synchronous | Control,Mode of metastases - N (%) | Metachronous | Treatment,Mode of metastases - N (%) | Metachronous | Control,Volume of disease - N (%) | High | Treatment,Volume of disease - N (%) | High | Control,Volume of disease - N (%) | Low | Treatment,Volume of disease - N (%) | Low | Control
0,NCT00104715,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",26610858,GETUG-AFU15,Gravis G et al,2015,Follow up,128 (67),144 (75),62 (32),46 (24),92 (48),91 (47),100 (52),102 (53)
1,NCT00268476,Abiraterone acetate 1000mg OD + Prednisolone 5...,35411939,STAMPEDE,James N et al,2022,Follow up,466 (93),475 (95),35 (7),27 (5),243 (48.5),256 (51),206 (41.1),196 (39.0)
2,NCT00268476,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",34757812,STAMPEDE,Rush L et al,2020,Follow up,345 (95),688 (95),17 (5),54 (5),148 (41),320 (44),124 (34),238 (34)
3,NCT00268476,Enzalutamide 160mg OD; Abiraterone acetate 100...,37142371,STAMPEDE,Attard E et al,2023,Follow up,None,None,None,None,196 (42),209 (46),195 (42),162 (36)
4,NCT00309985,"Docetaxel 6 cycles at 75mg/m²/cycle, one cycle...",29384722,CHAARTED,Kyriakopoulos C et al,2018,Follow up,289 (72.8),286 (72.8),108 (27.2),106 (27.0),263 (66.2),250(63.6),134 (33.8),143 (36.4)
5,NCT01715285,Abiraterone acetate 1000mg OD + Prednisolone 5...,30987939,LATITUDE,Fizazi K et al,2019,Follow up,597 (100),602 (100),0 (0),0 (0),487 (81.6),468 (77.7),110 (18.4),133 (22.1)
6,NCT01809691,TAK 300 mg BD; Standard androgen deprivation,35446628,SWOG1216,Agarawal N et al,2022,Original,None,None,None,None,None,None,None,None
7,NCT01957436,Abiraterone acetate 1000mg OD + Prednisolone 5...,35405085,PEACE-1,Fizazi K et al,2022,Original,583 (100),589 (100),0 (0),0 (0),331 (57),336 (57),252 (43),253 (43)
8,NCT02446405,Enzalutamide 160mg OD; Standard androgen depri...,36990608,ENZAMET,Sweeney J et al,2023,Follow up,335 (59.5),348 (61.9),228 (40.4),228 (38.1),301 (53.5),301 (53.5),262 (46.5),261 (46.4)
9,NCT02489318,Apalutamide 240 OD; standard androgen deprivation,10.1016/j.ejca.2023.113290,TITAN,Merseburger AS et al,2023,Follow up,411 (78.3),441 (83.7),85 (16.2),59 (11.2),325 (61.9),335 (63.6),200 (38.1),192 (36.4)
10,NCT02677896,Enzalutamide 160mg OD; Standard androgen depri...,35420921,ARCHES,Armstrong A et al,2022,Follow up,402 (70),365 (63.4),83 (14.5),86 (14.9),354 (61.7),373 (64.8),220 (38.3),203 (35.2)
11,NCT02799602,Darolutamide 600mg BID; Docetaxel 6 cycles at ...,36795843,ARASENS,Hussain M et al,2023,Follow up,558 (85.7),566 (86.5),86 (13.2),82 (12.5),497 (76.3),508 (77.6),154 (23.6),146 (22.3)

In [1]:

from react.llm_models import gpt4

In [18]:
%%time
treatment_abbreviations_template = f"""Transform detailed medical treatment regimens into their abbreviated forms. The goal is to simplify complex treatment descriptions for easier analysis and comparison."
Transformation Rules:

"Use acronyms or the first letter(s) of each drug's name to create abbreviations."
"Concatenate multiple treatments with a '+' sign."
"Use well-known abbreviations for common treatment types (e.g., ADT for androgen deprivation therapy)."
"Exclude supportive treatments unless they are a primary component of the therapy."
Example Shots:

Original: "Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation"
Abbreviated: "Docetaxel + ADT"

Original: "Enzalutamide 160mg OD; Abiraterone acetate 1000mg OD + Prednisolone 5mg BID; Standard androgen deprivation"
Abbreviated: "Enzalutamide + Abiraterone + ADT"

Original: "Darolutamide 600mg BID; Docetaxel 6 cycles at 75mg/m²/cycle, one cycle every 3 weeks; Standard androgen deprivation"
Abbreviated: "DARO + D + ADT"

Instructions:
Based on these examples, create abbreviations for the following treatment regimens: {unique_treatment_regimens}. Please provide the output in a Python-friendly format, such as a list of tuples or key-value pairs, where the first element is the original regimen and the second element is its abbreviation. Please follow this format for each treatment regimen:
("Original Regimen", "Abbreviated Regimen").
"""
abbr_response = gpt4(treatment_abbreviations_template, 'task1a')
abbr_response

In [18]:
# Parsing the provided string to extract the treatment regimens and their abbreviations